### ISSUE TITLE
Add support for fileContent objects in SARIF export

### ISSUE THREAD

**Issue by seer79** [ispras/casr#157]
SARIF may include full content of files via fileContent  objects (section 3.2 in the specification). It would be good to add cmd line flag to enable this feature while exporting SARIF.

Including file content in SARIF would simplify importing data in other tool and provide visualization without the need of original source code.

**Comment by hkctkuy** [comment]
@seer79
Can you please send a link to the sarif specification where you read about such  objects, because I read [this](https://docs.oasis-open.org/sarif/sarif/v2.1.0/csprd01/sarif-v2.1.0-csprd01.html#_Toc10540859). And section 3.2 is about file naming convention here.
Also there is no `fileContent object` section here, but  `artifactContent object` section [is represent](https://docs.oasis-open.org/sarif/sarif/v2.1.0/csprd01/sarif-v2.1.0-csprd01.html#_Toc10540860), maybe that's what you meant?

**Comment by seer79** [comment]
In the latest version it is in 'contents' property of an Artifact. The schema is '#/definitions/artifactContent' ( artifactContent object (§3.3))
Please use 'text' property of artifactContent for source code
